import React, { FC } from 'react';
import AnimatedText from '../../../AnimatedText/AnimatedText';

import styles from './AnimatedTitle.module.scss';

interface AnimatedTitleProps {}

const AnimatedTitle: FC<AnimatedTitleProps> = () => {
  return (
    <div className={styles.AnimatedTitle}>
      <h1>
        <AnimatedText appearingAnimation="roll-in-left" animationName="spin" delay={250} text="H" />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          animationName="rubber-band"
          delay={450}
          text="e"
        />
        <AnimatedText
          appearingAnimation="bounce-in-forward"
          animationName="rubber-band"
          delay={350}
          text="l"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          animationName="rubber-band"
          delay={400}
          text="l"
        />
        <AnimatedText
          appearingAnimation="bounce-in-forward"
          animationName="rubber-band"
          delay={450}
          text="o"
        />{' '}
        <AnimatedText appearingAnimation="roll-in-left" animationName="spin" delay={500} text="W" />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          animationName="rubber-band"
          delay={700}
          text="o"
        />
        <AnimatedText
          appearingAnimation="bounce-in-forward"
          animationName="rubber-band"
          delay={750}
          text="r"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          animationName="rubber-band"
          delay={800}
          text="l"
        />
        <AnimatedText
          appearingAnimation="bounce-in-forward"
          animationName="rubber-band"
          delay={850}
          text="d"
        />{' '}
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          animationName="rubber-band"
          delay={900}
          text="!"
        />{' '}
        <span role="img" aria-label="émoji main qui fait coucou">
          <AnimatedText
            appearingAnimation="wave-appear"
            animationName="wave"
            delay={1000}
            text="👋🏻"
          />
        </span>
        <br />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={350}
          animationName="rubber-band"
          text="M"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={400}
          animationName="rubber-band"
          text="o"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={450}
          animationName="rubber-band"
          text="i"
        />{' '}
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={500}
          animationName="rubber-band"
          text="c"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={550}
          animationName="rubber-band"
          text="'"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={600}
          animationName="rubber-band"
          text="e"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={650}
          animationName="rubber-band"
          text="s"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={700}
          animationName="rubber-band"
          text="t"
        />{' '}
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={650}
          animationName="rubber-band"
          text="D"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={700}
          animationName="rubber-band"
          text="a"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={750}
          animationName="rubber-band"
          text="v"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={800}
          animationName="rubber-band"
          text="i"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={850}
          animationName="rubber-band"
          text="d"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={850}
          animationName="rubber-band"
          text=","
        />{' '}
        <br />
        <AnimatedText
          appearingAnimation={'roll-in-left'}
          delay={600}
          animationName="spin"
          text="d"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={950}
          animationName="rubber-band"
          text="é"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1000}
          animationName="rubber-band"
          text="v"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1050}
          animationName="rubber-band"
          text="e"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1100}
          animationName="rubber-band"
          text="l"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1150}
          animationName="rubber-band"
          text="o"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1200}
          animationName="rubber-band"
          text="p"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1250}
          animationName="rubber-band"
          text="p"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1300}
          animationName="rubber-band"
          text="e"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1350}
          animationName="rubber-band"
          text="u"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1400}
          animationName="rubber-band"
          text="r"
        />{' '}
        <AnimatedText
          appearingAnimation={'roll-in-left'}
          delay={1000}
          animationName="spin"
          text="w"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1500}
          animationName="rubber-band"
          text="e"
        />
        <AnimatedText
          appearingAnimation="bounce-in-appear"
          delay={1550}
          animationName="rubber-band"
          text="b"
        />
        <AnimatedText
          appearingAnimation={'bounce-in-top'}
          delay={1500}
          animationName="rubber-band"
          text="."
        />{' '}
      </h1>
      <h2>
        <AnimatedText
          appearingAnimation="slit-in"
          delay={900}
          animationName="pulsate"
          text="Développeur"
        />{' '}
        <AnimatedText
          appearingAnimation="slit-in"
          delay={900}
          animationName="pulsate"
          text="JavaScript"
        />
      </h2>
    </div>
  );
};

export default AnimatedTitle;
